name: fake_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  json_annotation: ^4.8.0
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
